spring:
    profiles:
        active:
            - dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver # in most of cases is not required
        url: jdbc:mysql://localhost:3306/taco_cloud?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: 1234
        initialization-mode: always
        schema:
        - classpath:sql/ingredient.sql
        - classpath:sql/schema.sql
        # data:
        # - classpath:sql/data.sql
    jpa:
        hibernate:
            ddl-auto: none
    kafka:
        bootstrap-address: localhost:9092
        template:
            default-topic: tacocloud.orders.topic
        producer:
            key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: earliest
        properties:
            spring:
                json:
                    trusted:
                        packages: '*'

server:
    port: 8080

taco:
    orders:
        pageSize: 20
        pageSizeMessage: Total orders per page ${taco.orders.pageSize}.

---
spring:
    profiles:
        - prod

server:
    port: 8002