spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver # in most of cases is not required
        url: jdbc:mysql://localhost:3306/taco_cloud?useSSL=false
        username: root
        password: 1234
        initialization-mode: always
        schema:
        - classpath:sql/ingredient.sql
        - classpath:sql/schema.sql
        data:
        - classpath:sql/data.sql
    jpa:
        hibernate:
            ddl-auto: none

server:
    port: 8002